const userData = [
  {
    id: 1,
    customer: 11901,
    customer_profile: {
      id: 11901,
      name: "Ram",
      color: [182, 73, 99],
      email: "ram@domain.com",
      pincode: "400001",
      location_name: "Mumbai, Maharashtra, India",
      type: "C",
      profile_pic: null,
      gst: "",
    },
  },
  {
    id: 2,
    customer: 11902,
    customer_profile: {
      id: 11902,
      name: "Sita",
      color: [34, 139, 34],
      email: "sita@domain.com",
      pincode: "500001",
      location_name: "Hyderabad, Telangana, India",
      type: "C",
      profile_pic: null,
      gst: "",
    },
  },
  {
    id: 3,
    customer: 11903,
    customer_profile: {
      id: 11903,
      name: "Laxman",
      color: [255, 165, 0],
      email: "laxman@domain.com",
      pincode: "600001",
      location_name: "Chennai, Tamil Nadu, India",
      type: "C",
      profile_pic: null,
      gst: "",
    },
  },
  {
    id: 4,
    customer: 11904,
    customer_profile: {
      id: 11904,
      name: "Bharat",
      color: [70, 130, 180],
      email: "bharat@domain.com",
      pincode: "700001",
      location_name: "Kolkata, West Bengal, India",
      type: "C",
      profile_pic: null,
      gst: "",
    },
  },
  {
    id: 5,
    customer: 11905,
    customer_profile: {
      id: 11905,
      name: "Hanuman",
      color: [128, 0, 128],
      email: "hanuman@domain.com",
      pincode: "110001",
      location_name: "New Delhi, India",
      type: "C",
      profile_pic: null,
      gst: "",
    },
  },
  {
    id: 6,
    customer: 11906,
    customer_profile: {
      id: 11906,
      name: "Krishna",
      color: [0, 128, 128],
      email: "krishna@domain.com",
      pincode: "380001",
      location_name: "Ahmedabad, Gujarat, India",
      type: "C",
      profile_pic: null,
      gst: "",
    },
  },
  {
    id: 7,
    customer: 11907,
    customer_profile: {
      id: 11907,
      name: "Radha",
      color: [255, 0, 0],
      email: "radha@domain.com",
      pincode: "500081",
      location_name: "Hyderabad, Telangana, India",
      type: "C",
      profile_pic: null,
      gst: "",
    },
  },
  {
    id: 8,
    customer: 11908,
    customer_profile: {
      id: 11908,
      name: "Jesus",
      color: [0, 0, 255],
      email: "jesus@domain.com",
      pincode: "411001",
      location_name: "Pune, Maharashtra, India",
      type: "C",
      profile_pic: null,
      gst: "",
    },
  },
  {
    id: 9,
    customer: 11909,
    customer_profile: {
      id: 11909,
      name: "Buddha",
      color: [255, 255, 0],
      email: "buddha@domain.com",
      pincode: "570001",
      location_name: "Mysore, Karnataka, India",
      type: "C",
      profile_pic: null,
      gst: "",
    },
  },
  {
    id: 10,
    customer: 11910,
    customer_profile: {
      id: 11910,
      name: "Zoroaster",
      color: [165, 42, 42],
      email: "zoroaster@domain.com",
      pincode: "682001",
      location_name: "Kochi, Kerala, India",
      type: "C",
      profile_pic: null,
      gst: "",
    },
  },
];

export default userData;
